"use client";
import {
  IconAlarm,
  IconAlertTriangle,
  IconApi,
  IconArchive,
  IconArrowsExchange,
  IconBadge,
  IconBarcode,
  IconBolt,
  IconBook,
  IconBookmark,
  IconBraces,
  IconBrowser,
  IconBug,
  IconBuilding,
  IconCalculator,
  IconCalendar,
  IconCamera,
  IconChartBar,
  IconChartDots3,
  IconChartLine,
  IconChartPie,
  IconClipboard,
  IconClock,
  IconClockHour4,
  IconCloud,
  IconCode,
  IconCoin,
  IconConfetti,
  IconCreditCard,
  IconCurrencyDollar,
  IconDatabase,
  IconDevices,
  IconDice,
  IconEdit,
  IconFeather,
  IconFile,
  IconFileCv,
  IconFileText,
  IconFilter,
  IconFingerprint,
  IconFlag,
  IconFlask,
  IconGasStation,
  IconGauge,
  IconGhost2,
  IconGift,
  IconGlobe,
  IconHash,
  IconHeadphones,
  IconHeart,
  IconHome,
  IconHtml,
  IconId,
  IconJson,
  IconKey,
  IconKeyboard,
  IconLanguage,
  IconLetterCase,
  IconLink,
  IconList,
  IconLock,
  IconMail,
  IconMap,
  IconMarkdown,
  IconMath,
  IconMicrophone,
  IconMoon,
  IconMusic,
  IconPalette,
  IconPencil,
  IconPhone,
  IconPhoto,
  IconPizza,
  IconPlanet,
  IconQrcode,
  IconQuestionMark,
  IconReceipt,
  IconRegex,
  IconRocket,
  IconSearch,
  IconSettings,
  IconShare,
  IconShield,
  IconSortAscending,
  IconStar,
  IconTable,
  IconTag,
  IconTerminal2,
  IconTestPipe,
  IconTicket,
  IconTool,
  IconTransform,
  IconTypography,
  IconUpload,
  IconUser,
  IconVideo,
  IconWand,
  IconWorld,
  IconZip,
  type Icon,
} from "@tabler/icons-react";

export const TOOL_ICONS: Record<string, Icon> = {
  IconAlarm,
  IconAlertTriangle,
  IconApi,
  IconArchive,
  IconArrowsExchange,
  IconBadge,
  IconBarcode,
  IconBolt,
  IconBook,
  IconBookmark,
  IconBraces,
  IconBrowser,
  IconBug,
  IconBuilding,
  IconCalculator,
  IconCalendar,
  IconCamera,
  IconChartBar,
  IconChartDots3,
  IconChartLine,
  IconChartPie,
  IconClipboard,
  IconClock,
  IconClockHour4,
  IconCloud,
  IconCode,
  IconCoin,
  IconConfetti,
  IconCreditCard,
  IconCurrencyDollar,
  IconDatabase,
  IconDevices,
  IconDice,
  IconEdit,
  IconFeather,
  IconFile,
  IconFileCv,
  IconFileText,
  IconFilter,
  IconFingerprint,
  IconFlag,
  IconFlask,
  IconGasStation,
  IconGauge,
  IconGhost2,
  IconGift,
  IconGlobe,
  IconHash,
  IconHeadphones,
  IconHeart,
  IconHome,
  IconHtml,
  IconId,
  IconJson,
  IconKey,
  IconKeyboard,
  IconLanguage,
  IconLetterCase,
  IconLink,
  IconList,
  IconLock,
  IconMail,
  IconMap,
  IconMarkdown,
  IconMath,
  IconMicrophone,
  IconMoon,
  IconMusic,
  IconPalette,
  IconPencil,
  IconPhone,
  IconPhoto,
  IconPizza,
  IconPlanet,
  IconQrcode,
  IconReceipt,
  IconRegex,
  IconRocket,
  IconSearch,
  IconSettings,
  IconShare,
  IconShield,
  IconSortAscending,
  IconStar,
  IconTable,
  IconTag,
  IconTerminal2,
  IconTestPipe,
  IconTicket,
  IconTool,
  IconTransform,
  IconTypography,
  IconUpload,
  IconUser,
  IconVideo,
  IconWand,
  IconWorld,
  IconZip,
};

export const TOOL_ICON_NAMES = Object.keys(TOOL_ICONS).sort();

export function getToolIcon(name: string): Icon {
  return TOOL_ICONS[name] ?? IconQuestionMark;
}

export function ToolIcon({
  name,
  size = 18,
  stroke = 1.7,
  className,
}: {
  name: string;
  size?: number;
  stroke?: number;
  className?: string;
}) {
  const Cmp = getToolIcon(name);
  return <Cmp size={size} stroke={stroke} className={className} />;
}
